version: '3.8'
services:
  # データベース(PostgreSQL)のコンテナ設定
  db:
    image: postgres:14-alpine
    container_name: task-app-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # アプリケーションのコンテナ設定
  app:
    build: .
    container_name: task-app-app
    ports:
      - "8080:8080"
    environment:
      # アプリが接続しにいくDBの場所を指定
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskapp
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db # dbコンテナが起動してからappコンテナを起動する

volumes:
  postgres_data: