CREATE TABLE IF NOT EXISTS task (
 id BIGSERIAL PRIMARY KEY,
 title TEXT NOT NULL,
 description TEXT,
 task_status VARCHAR(50) NOT NULL,
 due_date date,
 created_at TIMESTAMP NOT NULL DEFAULT NOW(),
 updated_at TIMESTAMP NOT NULL DEFAULT NOW()
)
;

CREATE TABLE IF NOT EXISTS user (
 user_id BIGSERIAL PRIMARY KEY,
 user_name TEXT NOT NULL,
 password TEXT,
 role VARCHAR(50) NOT NULL
)
;

