# GitHub Actionsのワークフロー名を定義します
name: Deploy to Amazon ECS

# このワークフローが実行されるタイミングを定義します
on:
  # mainブランチにpushされたときに実行されます
  push:
    branches:
      - main

# 環境変数を定義します
env:
  ECR_REPOSITORY: task-app
  AWS_REGION: ap-southeast-2
  # ECSのタスク定義ファミリー名を指定
  ECS_TASK_DEFINITION_FAMILY: task-app-def
  # ECSのサービス名を指定
  ECS_SERVICE_NAME: task-app-def-service
  # ECSのクラスター名を指定
  ECS_CLUSTER_NAME: task-app-cluster
  # タスク定義内のコンテナ名を指定（AWSで確認した名前にしてください）
  ECS_CONTAINER_NAME: task-app

jobs:
  # build-and-deployという名前のジョブを定義します
  build-and-deploy:
    # このジョブが実行される仮想環境を指定します（Ubuntuの最新版）
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # ジョブのステップを定義します
    steps:
      # 1. リポジトリのコードをチェックアウトします
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. AWSの認証情報を設定します
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: